version: '3.8'

services:
  mariadb:
    image: bitnami/mariadb:latest
    restart: always
    ports:
      - "33061:3306"
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: mydb13
      MARIADB_PASSWORD: 'root'
    volumes:
      - ./create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
    networks:
      - default

networks:
  default:
