version: '3.8'

services:
  mariadb:
    image: bitnami/mariadb:latest
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: mydb13
      #MARIADB_USER: root
      MARIADB_ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
      - ./mariadb_data:/bitnami/mariadb
    networks:
      - default

networks:
  default: